# Generated by Django 5.1.4 on 2025-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
