# Generated by Django 5.1.4 on 2025-01-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='car',
            new_name='product',
        ),
    ]
