# Generated by Django 5.1.5 on 2025-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_carmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating between 1 (worst) and 5 (best)'),
        ),
    ]
