# Generated by Django 5.1.5 on 2025-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_carmodel_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='hashtags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
