# Generated by Django 5.1.5 on 2025-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_carmodel_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='hashtags',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
